const C=[["Louise Banks","Arrival","Film"],["Lyra Belacqua","His Dark Materials","Roman / série"],["Donna Noble","Doctor Who","Série"],["Clara Oswald","Doctor Who","Série"],["Rose Tyler","Doctor Who","Série"],["Seven of Nine","Star Trek: Voyager","Série"],["Kathryn Janeway","Star Trek: Voyager","Série"],["Kira Nerys","Star Trek: DS9","Série"],["Faith Lehane","Buffy","Série"],["Cordelia Chase","Buffy","Série"],["Nancy Downs","The Craft","Film"],["Bonnie Bennett","The Vampire Diaries","Série"],["Caroline Forbes","The Vampire Diaries","Série"],["Eve Polastri","Killing Eve","Série"],["Claire Underwood","House of Cards","Série"],["Leslie Knope","Parks and Recreation","Série"],["Peggy Olson","Mad Men","Série"],["Joan Holloway","Mad Men","Série"],["Daria Morgendorffer","Daria","Dessin animé"],["Diane Nguyen","BoJack Horseman","Dessin animé"],["Shego","Kim Possible","Dessin animé"],["Toph Beifong","Avatar","Dessin animé"],["Suki","Avatar","Dessin animé"],["Princess Bubblegum","Adventure Time","Dessin animé"],["Garnet","Steven Universe","Dessin animé"],["Pearl","Steven Universe","Dessin animé"],["Adora","She-Ra","Dessin animé"],["Catra","She-Ra","Dessin animé"],["Velma Dinkley","Scooby-Doo","Dessin animé"],["Daphne Blake","Scooby-Doo","Dessin animé"],["Jessica Rabbit","Who Framed Roger Rabbit","Film / animation"],["Belle","La Belle et la Bête","Animation"],["Tiana","La Princesse et la Grenouille","Animation"],["Rapunzel","Raiponce","Animation"],["Elsa","La Reine des Neiges","Animation"],["Anna","La Reine des Neiges","Animation"],["Arwen","Le Seigneur des Anneaux","Roman / film"],["Ygritte","Game of Thrones","Série"],["Yara Greyjoy","Game of Thrones","Série"],["Astrid","Vikings","Série"],["Kida","Atlantide","Animation"],["Lucy Pevensie","Narnia","Roman / film"],["Susan Pevensie","Narnia","Roman / film"],["Mabel Pines","Gravity Falls","Dessin animé"],["Jane Eyre","Jane Eyre","Roman"],["Elizabeth Bennet","Orgueil et Préjugés","Roman"],["Fantine","Les Misérables","Roman"],["June Osborne","The Handmaid's Tale","Série"],["Lorelai Gilmore","Gilmore Girls","Série"],["Rory Gilmore","Gilmore Girls","Série"],["Martha Jones","Doctor Who","Série"],["Sarah Jane Smith","Doctor Who","Série"],["Amy Wong","Futurama","Dessin animé"],["April Ludgate","Parks and Recreation","Série"],["Liz Lemon","30 Rock","Série"],["Jessica Drew","Marvel","Comics"],["Kate Bishop","Marvel","Comics / série"],["Kamala Khan","Marvel","Comics / série"],["Rogue","Marvel","Comics / animation"],["Storm","Marvel","Comics / animation"],["Zatanna","DC","Comics"],["Black Canary","DC","Comics"],["Lois Lane","DC","Comics"],["Barbara Gordon","DC","Comics"],["Mera","DC","Comics"],["Starfire","DC","Comics / animation"],["She-Hulk","Marvel","Comics / série"],["Aeon Flux","Aeon Flux","Animation"],["Gwen Tennyson","Ben 10","Dessin animé"],["Mai","Avatar","Dessin animé"],["Ty Lee","Avatar","Dessin animé"]];

const K="tournoi-personnages-v1";let s=JSON.parse(localStorage.getItem(K)||"null")||{fight:1,streak:0,champ:null,chall:null,used:[],history:[]};
const id=c=>c[0]+"|"+c[1], pool=()=>C.filter(c=>!s.used.includes(id(c))&&(!s.champ||id(c)!==id(s.champ))), pick=()=>pool()[Math.floor(Math.random()*pool().length)];
function save(){localStorage.setItem(K,JSON.stringify(s))}
function initials(n){return n.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function show(el,c){el.querySelector("i").textContent=initials(c[0]);el.querySelector("h2").textContent=c[0];el.querySelector("p").textContent=c[1]+" • "+c[2]}
function render(){fight.textContent=s.fight;streak.textContent=s.streak;count.textContent=s.history.length;champName.textContent=s.champ?.[0]||"—";if(s.champ)show(left,s.champ);if(s.chall)show(right,s.chall);rows.innerHTML=s.history.slice().reverse().map(r=>`<div class="row">#${r.fight} — <b>${r.champ}</b> 🆚 ${r.chall} → 🏆 <b>${r.winner}</b><div class="meta">${r.universe} • ${r.media}</div></div>`).join("")||"Aucun combat terminé."}
function start(){if(!s.champ){s.champ=C[Math.floor(Math.random()*C.length)];s.used=[id(s.champ)];s.chall=pick();s.used.push(id(s.chall));save()}render()}
function choose(w){let win=w==="champ"?s.champ:s.chall,lose=w==="champ"?s.chall:s.champ;s.history.push({fight:s.fight,champ:s.champ[0],chall:s.chall[0],winner:win[0],universe:lose[1],media:lose[2]});if(w==="champ")s.streak++;else{s.champ=win;s.streak=1}s.fight++;s.chall=pick();if(s.chall)s.used.push(id(s.chall));save();render()}
left.querySelector("button").onclick=()=>choose("champ");right.querySelector("button").onclick=()=>choose("chall");
reset.onclick=()=>{if(confirm("Recommencer ?")){localStorage.removeItem(K);location.reload()}}
export.onclick=()=>{let a=[["Combat","Champion avant","Adversaire","Univers","Média","Gagnant"],...s.history.map(r=>[r.fight,r.champ,r.chall,r.universe,r.media,r.winner])];let b=new Blob(["\ufeff"+a.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(";")).join("\n")],{type:"text/csv;charset=utf-8"}),x=document.createElement("a");x.href=URL.createObjectURL(b);x.download="historique-tournoi.csv";x.click()};
start();